### ISSUE TITLE
Make error on Git Bash on Windows 10 Pro

### ISSUE THREAD

**Issue by yanalanhe** [ethereum-oasis/baseline#127]
## Expected Behavior
Running "make && make start && make test" works on Git Bash in Windows 10

## Actual Behavior
Under "baseline" folder, running "make && make start && make test" generated following build error:
> radish-34@1.0.0 build C:\Users\alan8\project\radish34\baseline\radish34
> ./ops/build.sh

'.' is not recognized as an internal or external command,"

Note: I think the error occurred at following line in package.json:
"scripts": {
    "await-stack": "./ops/await_stack.sh",
    "build": "./ops/build.sh",
    .....
}
Question: 
1) How to customize the Makefile or other to have Make working on Git Bash Windows 10 Pro?
2) Can the Radish34 application be running on localhost on Windows 10 Pro?

## Steps to Reproduce the Problem

  1. On Git Bash in Windows 10 Pro, change folder "baseline"
  2. Run command "make && make start && make test"
 
## Specifications

  - Version: 10.0.18363 Build 18363
  - Platform: Windows 10 Pro
  - Subsystem: Git Bash

**Comment by breakpointer** [comment]
@yanalanhe Any chance you could try and fix this and submit a PR?

**Comment by yanalanhe** [comment]
@breakpointer Please close this ticket. Now I found install and compile Baseline project is not applicable on Git Bash on Windows. The proper approach is to have Baseline project installed and compiled on a Linux or MacOS box. I've installed Baseline on a Ubuntu environment. Thanks.
