### ISSUE TITLE
Change the zkp service vk GET method to receive param via URL not body

### ISSUE THREAD

**Issue by Perseverance** [ethereum-oasis/baseline#129]
The current zkp service `/vk` endpoint returns the verification key based on the id of the circuit. The id param is currently passed as `id` param in the body of the request. As this is non standard for `GET` requests this should either be changed to URL param or change the request type.

**Comment by kthomas** [comment]
I have this change on a branch. Will see if I can cherry-pick it and make a PR.

**Comment by Perseverance** [comment]
That would be wonderful, If you need help in addressing the change in the resolver, I can help there
