### ISSUE TITLE
Create New Purchased Order failed

### ISSUE THREAD

**Issue by yanalanhe** [ethereum-oasis/baseline#145]
## Expected Behavior
Request to Create New Purchased Order will have a new PO created.

## Actual Behavior
1) Create New Purchased Order failed. It crashed due to calling getLeafByLeafIndex() in merkle-tree.js returned null (body.data = { error: null, data: null }). The error logs:

![image](https://user-images.githubusercontent.com/43561509/81239379-b32a0100-8fd2-11ea-9f76-5d7e04e244ad.png)

![image](https://user-images.githubusercontent.com/43561509/81240223-d0f86580-8fd4-11ea-92dc-581e4d004530.png)

 2) In connecting shared-merkle-mongo image with mongo client, the db collection "admin_shield_metadatas" did not contain the MSA's commitment in the  merkle- tree leave. (Is the latest MSA's commitment stored in this collection?  )

## Steps to Reproduce the Problem

  1. Buyer created a RFP for Supplier 2
  2. Supplier 2 created the proposal with 3 tiers 
      {Volume : Price}: {200:$10} {400:$9} {600:$8}
  3. Buyer created the MFA
  4. On Create New Purchased Order, Buyer selected the newly created MFA and clicked Send Purchased Order button

## Specifications
  - Version: 18.04
  - Platform:Ubuntu 
  - Subsystem: Baseline Radish34

**Comment by yanalanhe** [comment]
There are more findings related to this bug. **The service mongo-merkle-tree's db collection "admin_shield_nodes" appeared not be populated with leaves and nodes from on-chain.** 

Whenever I created a MSA successfully with commitment index, I query the service mongo-merkle-tree with following command: 
curl -H "contractname:Shield" http://localhost:9000/leaf/index/{leaf index for the new commitment}

The response from shared-merkle-mongo:
src/routes/leaf.routes getLeafByLeafIndex()
req.params:
{ leafIndex: '7' }
req.body:
{}

src/db/service/leaf.service getLeafByLeafIndex()
Mongoose: admin_shield_nodes.findOne({ leafIndex: 7 }, { projection: {} })

src/db/mongodb/db getDoc()

**Comment by wenxing-wang-ey** [comment]
@yanalanhe I think this is a timing issue. You need to wait for the createMSA transaction to complete first - in the api-buyer container log, you should wait until you see:

CREATE MSA TRANSACTION COMPLETE
Updated MSA with new commitment index

Then you can start to createPO.

**Comment by humbitious** [comment]
@yanalanhe and team, let me know if this is resolved or if we can close.

**Comment by yanalanhe** [comment]
@humbitious @wenxing-wang-ey We changed our code base so retesting this can't be done at current time. I think this will be not an issue as long as we wait for the createMSA transaction to complete first. Thanks you for all your help.
