### ISSUE TITLE
Handle participant registration and onboarding 

### ISSUE THREAD

**Issue by yanalanhe** [ethereum-oasis/baseline#157]
We would like to know the specific procedures of how to handle participant registration and onboarding. @skarred14 replied from Baseline Slack as follows:

_"registration as a ui feature is not fully built in. It is handled as a backend fixture: create a workgroup, and then register individual participants against a registry contract. This is how the process works during deploy step in make start. If you were to add a custom registry, one could follow a similar process. Ideally, we could think of each participant as a scale set of services: api, zkp, messenger, dbs. As long as each such scale set is connected to a commonly accessible network like ganache or ropsten etc., existing format of registration can be extended or customized. Regdless we ll discuss this topic, if you'd like feel free to create an issue on the repo, as a discussion item"_

**Comment by humbitious** [comment]
Seems like this is part of the corp identity epic, no?  (Note: the current thinking is that baselining stops at the edge of the company/org. It's the organization's endpoint and account pointer that the protocol deals with. Users within an org would be managed by internal systems as normal. And imo, there is no need for individual users in this protocol to have wallets or endpoint management unto themselves, though that is grounds for discussion.

**Comment by kthomas** [comment]
This is included in `init-core` within the `core/api` package and demonstrated within the new reference implementation.
