### ISSUE TITLE
Add NATS as messenger alternative to Whisper

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#165]
## Overview

In order to accelerate wide-spread adoption, baseline needs a scalable, production-ready messaging solution. Whisper served its purpose for the radish34 demo, but has issues with throughput and message delivery success on large networks. NATS is a production quality option already in-use and trusted by enterprises.

### Reference

- [NATS docs](https://docs.nats.io/)
- [NATS architecture](https://github.com/nats-io/nats-general/blob/master/architecture/ARCHITECTURE.md)

### Implementation

- Each baseline user will run their own NATS server container. The NATS server receives messages on an endpoint shared with other baseline users
- NATS will be supported by the `@baseline-protocol/messaging` npm package
- Whisper will be supported by the `@baseline-protocol/messaging` npm package

This work is part of the [init-core](https://github.com/ethereum-oasis/baseline/tree/init-core) branch.

### Questions

- Should we implement authentication of message sender using JWTs?

### Acceptance

- [x] NATS should be a top-level configuration option for baseline users
- [x] NATS will be supported by the `@baseline-protocol/messaging` npm package
- [x] Tests are added to cover messaging using NATS as the provider
- [x] Documentation is added to explain messaging configuration and NATS architecture

**Comment by kthomas** [comment]
Closing this.
