### ISSUE TITLE
Blockchain Explorer

### ISSUE THREAD

**Issue by stefschmidt** [ethereum-oasis/baseline#177]
“Transthereum”, a blockchain explorer comparable to etherscan, executable on local developer machines to have an easier access and monitoring, e.g to Ganache.
Code is copied based on the open-source implementation from Unibright (https://github.com/unibrightIO/Transthereum) and will be added in the "lib" section of the init-core branch

**Comment by kthomas** [comment]
This has been added to the init-core branch but needs to be moved into the right place still.

Will move it into place before we merge init-core.
