### ISSUE TITLE
Quickstart missing setup instructions for Windows 10 users

### ISSUE THREAD

**Issue by KevinSmall** [ethereum-oasis/baseline#179]
## Expected Behavior
As a Windows user, I can follow quickstart instructions in https://github.com/ethereum-oasis/baseline/blob/master/README.md and get the radish34 demo working.

## Actual Behavior
The quickstart instructions in https://github.com/ethereum-oasis/baseline/blob/master/README.md assume Linux without saying so.

## Steps to Reproduce the Problem
n/a

**Comment by kthomas** [comment]
Closing this-- will be included in init-core merge to master...

https://github.com/ethereum-oasis/baseline/commit/500186b389925218ada968d062828d80c322383d
