### ISSUE TITLE
[Radish34] Import and use @baseline-protocol/api package

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#225]
## Overview

Now that the initial @baseline-protocol nodejs packages have been released, we should have more examples (besides bri-1) showing how they can be used. The Radish34 reference implementation was written before the baseline packages were built. The [api service](https://github.com/ethereum-oasis/baseline/tree/master/examples/radish34/api) within Radish34 should import and use the @baseline-protocol/api package as demonstrated by bri-1.

### Details

Since the @baseline-protocol/api package's RPC provider is not fully implemented yet, the radish34 api service can just use the general purpose [exec method]() for json-rpc requests to the geth node instead of the more specific `IBlockchainService` interface methods. 

### Reference

- [bri-1 use of @baseline-protocol/api](https://github.com/ethereum-oasis/baseline/blob/master/examples/bri-1/base-example/src/index.ts#L1)

### Acceptance

- Instead of using the `Provide` provider as in `bri-1`, radish34 should use RPC
- Existing radish34/api test suite should pass
- Existing radish34 integration test suite should pass

**Comment by erazhu31** [comment]
Hi i would to work on this issue, i looked at the file baseline/core/api/src/index.ts and there is already some implementation using 
Rpc instead of provider. Please give me some return what should be improve

**Comment by bitwiseguy** [comment]
Closing due to deprecation of Radish34
