### ISSUE TITLE
Docker needs 12.5 GB actually

### ISSUE THREAD

**Issue by marsrobertson** [ethereum-oasis/baseline#253]
### Running the demo:

https://github.com/ethereum-oasis/baseline/tree/master/examples/radish34

`make && make start && make test`

### On Mac:

![image](https://user-images.githubusercontent.com/44369284/98412988-cc3e6800-2070-11eb-8169-1149ac93a829.png)

Setting to 12 GB still complains.

Setting to 12.25 GB still complains.

Only after setting to 12.5 GB it works.

**Comment by bitwiseguy** [comment]
The radish README now recommends >= 12.5 GB
