### ISSUE TITLE
calculate-amount-owed; == supposed to be? 

### ISSUE THREAD

**Issue by Meuko** [ethereum-oasis/baseline#261]
https://github.com/ethereum-oasis/baseline/blob/4402142c4fd00ae0069146d4008f7bba6e76c42b/examples/radish34/zkp/circuits/business-logic/calculate-amount-owed.zok#L37

Is this intended; or is this supposed to be an assignment?

**Comment by myronrotter** [comment]
@Meuko, I am late to the party, but here is a short explanation.

In the context of the issue #224, I came across the ZoKrates circuits and tried to compile them via the `@baseline-protocol/privacy` zokrates provider.

This should not be an assignment. Those `==` statements are actually intended and represent assertions.
That's probably why the new syntax is as follows:
```
assert(newCumulativeVolume == oldCumulativeVolume + thisVolume)
```

**Comment by Meuko** [comment]
> @Meuko, I am late to the party, but here is a short explanation.
> 
> In the context of the issue #224, I came across the ZoKrates circuits and tried to compile them via the `@baseline-protocol/privacy` zokrates provider.
> 
> This should not be an assignment. Those `==` statements are actually intended and represent assertions.
> That's probably why the new syntax is as follows:
> 
> ```
> assert(newCumulativeVolume == oldCumulativeVolume + thisVolume)
> ```

Much appreciated, that's why I closed this issue; figured this out **before** I started writing my circuits in ZoKrates rather than copying and pasting from he repo. Much appreciated though! Cheers!
