### ISSUE TITLE
Potential security bug with the zk-SNARK verifier

### ISSUE THREAD

**Issue by weijiekoh** [ethereum-oasis/baseline#34]
## Expected Behavior

The `Verifier.verify()` function, not the function that calls it (i.e. `Shield.createMSA()` and `Shield.createPO()`, should require that each public input to the snark is less than the scalar field:

```
21888242871839275222246405745257275088548364400416034343698204186575808495617
```

## Actual Behavior

While the `Shield.createMSA()` and `Shield.createPO()` functions may not be vulnerable due to the way they hash some variables and check if the single public input matches the hash, other circuits in the future may be vulnerable if the developer does not do the required check.

To avoid this problem entirely, perform the check in the `Verifier.verify()` function. This bugfix should probably be done upstream in the Nightfall repository.

See also:

https://github.com/appliedzkp/semaphore/issues/16

https://github.com/EYBlockchain/nightfall/pull/96

**Comment by skarred14** [comment]
@weijiekoh thanks for the issue. Going over the linked issues, it looks like one of the ways this could be addressed is by validating all inputs in `inputs[]` are checked against the zk snark scalar field, perhaps something like this in `verificationCalculation` function in `Verifier.sol`: 
`require(input[i] < 21888242871839275222246405745257275088548364400416034343698204186575808495617)`. 
To your point, it would be good to have this as an upstream change even for the `export-verifier` functionality in `Zokrates` also addresses this range limit

**Comment by weijiekoh** [comment]
Yes, sounds good!

I recommend range-checking the proof elements as is done here:

https://github.com/appliedzkp/semaphore/blob/master/contracts/sol/verifier.sol#L199
