### ISSUE TITLE
computeWitness doesn't save createMSA_witness file

### ISSUE THREAD

**Issue by j4ys0n** [ethereum-oasis/baseline#41]
## Expected Behavior
Compute Witness & Generate Proof should succeed.

## Actual Behavior
Compute Witness doesn't save createMSA_witness file and proof generation fails.

## Steps to Reproduce the Problem

  1. create contract through front end

## Specifications

error:
```
Compute witness...
Generate proof...
Error: Generate proof failed: thread 'main' panicked at 'couldn't open ./output/createMSA/createMSA_witness: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:499:29
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
at Socket.zokrates.stderr.on.err (/app/node_modules/@eyblockchain/zokrates.js/lib/generate-proof.js:85:14)
```
i went into the container to look for the file and it is indeed not there.
```
root@db7db09ed294:/app/output/createMSA# ls -la
total 452904
drwxr-xr-x 7 root root       224 Mar 20 17:53 .
drwxr-xr-x 4 root root       128 Mar 20 17:53 ..
-rw-r--r-- 1 root root     25090 Mar 20 20:52 Verifier_createMSA.sol
-rw-r--r-- 1 root root  73119989 Mar 20 20:50 createMSA_out
-rw-r--r-- 1 root root  44069790 Mar 20 20:50 createMSA_out.ztf
-rw-r--r-- 1 root root 335299968 Mar 20 20:52 createMSA_pk.key
-rw-r--r-- 1 root root      1486 Mar 20 20:52 createMSA_vk.key
```

  - Version:
  - Platform: macOS 10.15, docker 2.2.0.4
  - Subsystem:

**Comment by skarred14** [comment]
@j4ys0n recent updates to master have removed redundant watch containers for api and zkp. Is this still an issue?

**Comment by j4ys0n** [comment]
Yes, I believe this is solved. I was able to get it to work the other day. Although now, after pulling the latest from master i'm having trouble with something else. Looking into it and will open a different ticket if needed.

Thank you!

**Comment by nicoSix** [comment]
Hi everybody,
I went across the same issue today, trying to create an MSA through the UI. 
@j4ys0n , did you do something particular to have it working?
