### ISSUE TITLE
unable to start dotdocker

### ISSUE THREAD

**Issue by sampsojp** [ethereum-oasis/baseline#48]
## Expected Behavior
successful start

## Actual Behavior
  > Start dotdocker containers
    > Start proxy
      √ Pulling codekitchen/dinghy-http-proxy:latest
      \ Creating dotdocker-proxy
        Starting dotdocker-proxy
    > Start dnsmasq
      √ Pulling andyshinn/dnsmasq:latest
      × Creating dotdocker-dnsmasq
        → (HTTP code 404) no such container - No such image: andyshinn/dnsmasq:latest

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by sampsojp** [comment]
sorry, should have titled unable to start dotdocker. installation was successful.

**Comment by breakpointer** [comment]
Thanks for reporting the issue @sampsojp I hope you were able to get it working. However, I am going to close it for two reasons: 
1) The error is not related to the baseline project 
2) It appears (at least based on my investigation) that [the image does exist](https://hub.docker.com/layers/andyshinn/dnsmasq/latest/images/sha256-831c17422076fc1dd66f61250f954ee6e0ae3183a0077d3838cda642c09c32b2?context=explore)

Please re-open and provide additional information about the issue if you feel it is something we should look into in further detail.
