### ISSUE TITLE
Reduce zkp integration test time

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#50]
## Overview

Currently the integration test suite (run by `make test`) takes several minutes to complete. All tests take less than a second, except for two tests that make calls to the zkp `/generateProof` endpoint.

### Reference

The generation of the proof is very time consuming. Your laptop has to whir away through lots of tedious elliptic curve operations for minutes. It’s nothing to do with the blockchain. Once the proof is generated (within the zokrates container), the act of sending the proof to the shield contract as a blockchain transaction is very quick (especially when using ganache).

> Note: the periodic "socket hangup" issue that produces test failures is caused by the long process time of POST /generateProof. This should be solved by replacing that http REST call with bulljs queues. That work is currently on the "development" branch and will be eventually merged into "master"

### Potential solution

What we could do is create a set of lazy dummy arithmetic circuits (i.e. dummy files for createMSA.zok and createPO.zok where the body of the function just contains a dummy line of useless code). This would make testing much faster. Developers would just have to be cautious when editing any of the backend zkp code (in case they break the "proper" .zok files).

> Note: createMSA.zok and createPO.zok  are already quite ‘simplified’  to reduce proving time, because the merkle tree being used only has 16 leaves (which takes a minute or two to generate the proof) , rather than 4 billion (which takes around 5 minutes). 

We could use the "dummy" circuits for integration testing and use the "real" circuits for unit testing of the `zkp` service.

**Comment by kthomas** [comment]
@skarred14 was this addressed by the Makefile effort?

**Comment by skarred14** [comment]
@kthomas @bitwiseguy 

this is a WIP but it has the dummy circuits, just need to build the integrations or switches for these dummy circuits.
https://github.com/ethereum-oasis/baseline/tree/dummy-circuits
