### ISSUE TITLE
Messaging Layer Specification

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline#63]

**Comment by eoinco** [comment]
Just getting some high level headings to cover as part of the specification. 

**Authentication**
 - JWT, authentication token, basic auth (username/password)
 - Initial handshake mechanisms
 - Address book considerations (x509, ENS, etc.)


**Security**
 - How will messages be encrypted in transit?  This is above the assumption that messaging will happen over TLS
 - Point-to-point direct connectivity vs. federated messaging with brokers conducting store-and-forward operations on messages
 - Key management (linked to authentication section)

**Connectivity**
 - Push vs. Pull considerations
 - Port considerations (operations over 443 port, or do we require a custom port with associated firewall rules to be implemented)

**Messaging Standards**
 - Interoperability with existing in-place enterprise messaging systems (kafka, rabbitMQ, NATS, XMPP, etc.) will be key to avoid restricting to sole commercial product.
