### ISSUE TITLE
Story: Tidying up the contracts deployment procedure and preparing it for baseline

### ISSUE THREAD

**Issue by Perseverance** [ethereum-oasis/baseline#88]
The current contracts deployment procedure for Radish34 is based on a nodejs project and custom deployments of several contracts. Although it works flowlessly for an MVP procedure, several improvements can be made to make it "baseline" ready:

### Separating and abstracting away, the deployment processes for client contracts and protocol contrats.

Current contracts deployment procedure is unified for every necessary contract in order to run Radish34 locally. Looking forward into abstracting this procedure, so that it becomes a part of baseline, the contracts can be separated in two categories.

- Protocol contracts - contracts that will be present on mainnet at the time of deployment and do not need to be deployed, but need to be deployed when using local environment. Ex. ERC1820Registry contract.
- Client contracts - contracts that will need to be deployed (and maintained - in future story) as part of the client setup - separate instance for every client. Ex. Org Registry, Shield, Verifier

We can create a mini-library that can be used to execute the procedure for both categories of contracts. This library will allow for configuring contracts, picking and choosing what to be deployed and generally perform the deployment process given the inputs. 

This library will become the core of the next story.

### Tidying up the code for better readability and maintenance

Currently the code uses custom wrappers around ethers and native ethers.js code for deployment of contracts. Most of these are already present in other ethers.js based deployment libraries like [etherlime-lib](https://etherlime.gitbook.io/etherlime/developer-documentation/etherlime-library-api/deployers). These will allow for reducing and tidying the codebase.

**Comment by Perseverance** [comment]
@breakpointer @skarred14 Can you guys assign me to this issue?

**Comment by skarred14** [comment]
Thanks for submitting this issue. Quick comment about ERC1820 in Protocol Contracts:
ERC1820Registry is already deployed on the mainnet at: `0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24`. For a mainnet deployment, minor changes are necessary in the current sol file constructors, to update this value, instead of re-deploying ERC1820Registry. Considering other alternative networks (Ropsten. Ganache, etc.) as targets could be a good aspect of the mini lib

**Comment by Perseverance** [comment]
@skarred14 Noted, I will account for that.

**Comment by Perseverance** [comment]
Closed by #109
