### ISSUE TITLE
Story: Non-interactive CLI - baseline-administrator - deployment part

### ISSUE THREAD

**Issue by Perseverance** [ethereum-oasis/baseline#89]
Depends on #88

----
Based on the mini-library described above a deployment (for now) CLI can be created. The CLI can become part of the baseline and Radish contracts deployment procedure.

The CLI will be non-interactive - it will expect parameters to be externally output via comand line parameters.

It will have several commands available. Working example of two commands would be:

- deploy-client - for deployment of client contracts
- deploy-protocol - for deployment of protocol contracts

Both of these commands will probably have their own separate set of parameters, but some of the common ones would be:

- deployer private key
- URL to mainnet node

etc.

**Comment by Perseverance** [comment]
@breakpointer @skarred14 Can you guys assign me to this issue

**Comment by skarred14** [comment]
In radish34 config/ has additional hard coded keys (account addresses and signature keys) used during deployment for OrgRegistry. Assuming this falls under deploy-client, does this story also cover how to manage/generate and handle such keys?

**Comment by Perseverance** [comment]
I'd rather keep the scope of this story to the keys being passed from outside, and make another one after that for keys generation. This should definitely be part of the baseline-administrator though.

**Comment by breakpointer** [comment]
Completed? If not, please re-open.
