### ISSUE TITLE
npm run deploy - Error: incorrect number of arguments

### ISSUE THREAD

**Issue by jeffprestes** [ethereum-oasis/baseline#95]
## Expected Behavior
Assigned the deployer as the manager for OrgRegistry. TxHash: 0x1689ac60fba5c25b5559e0fbca066c4063a433dec552adc9208977e161f05852

## Actual Behavior
Patiently waiting 10 seconds for ganache container to init ...
Checking for ganache ...
(node:9) UnhandledPromiseRejectionWarning: Error: incorrect number of arguments
    at Contract.assignManager (/app/node_modules/ethers/contract.js:130:19)
    at Object.assignManager (/app/src/utils/organization.js:29:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async assignManager (/app/src/deploy.js:39:31)
    at async main (/app/src/deploy.js:115:3)

## Steps to Reproduce the Problem

  1. Follow setup instructions until step 6

## Specifications

  - Version: latest
  - Platform: MacOs 10.15.4
  - Subsystem: node version v11.15.0

**Comment by bitwiseguy** [comment]
@jeffprestes I have not seen this error before. Are you using the latest code from the `master` branch and have you customized it in any way? Here are a few things to consider that could help solve the issue:

1. Clean out the blockchain data by removing that docker volume:
```docker volume rm radish34_chaindata```
2. Rebuild the `deploy` container to ensure it is not broken:
```docker-compose build deploy```
2. If you see the same error again, can you share the logs from the `ganache` container?
```docker logs ganache```

**Comment by jeffprestes** [comment]
Error persists. Looks like ganache container is not loading:

```bash
$ docker logs ganache
Error: No such container: ganache
``` 
Is there a way to start ganache container manually? 
Also, use GETH instead of Ganache would be safe, wouldn't be?

**Comment by skarred14** [comment]
@jeffprestes good catch! thanks. Recent merge from #90 seemed to have caused this issue. Take a look at #97 which should fix this bug
